name: Publish to Modrinth

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish to Modrinth
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine project versions
        id: versions
        run: |
          VERSION=$(cat version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

          MINECRAFT_VERSION=$(cat minecraft-version)
          echo "minecraft-version=$MINECRAFT_VERSION" >> "$GITHUB_OUTPUT"

          ARCHIVE_FILENAME=mojos-dice-roller-$VERSION-mc-$MINECRAFT_VERSION.zip
          echo "archive-filename=$ARCHIVE_FILENAME" >> "$GITHUB_OUTPUT"

          echo $GITHUB_EVENT_NAME # temporary - debug purposes

      - name: Archive repository as zip file
        run: git archive --format=zip --output=${{ steps.versions.outputs.archive-filename }} HEAD
